spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

jwt.secret=9a6747f6f124d769a643614f80f326b44469bcf35f12622b23f13a149423b5ad
jwt.expiration=300000


